use_frameworks!

platform :ios, '10.0'

target 'HKRxMoya_Example' do
  pod 'HKRxMoya', :path => '../'

  target 'HKRxMoya_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
